/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import control.koneksicari;
import gui.Dashboard;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Majey
 */
public class kasirumum extends javax.swing.JFrame {
DefaultTableModel tabModel;
ResultSet RsProduk=null;



    /**
     * Creates new form Dashboard
     */
    public kasirumum() {
        initComponents();
        table_update();
        hutangnya();
        typenya.setText(LoginSession.Nickname);
        wajib1.setVisible(false);
        ngayahna.setVisible(false);
        bacode1.setVisible(false);
        jButton6.setVisible(false);
        wajibteks.setVisible(false);
        wajibminus.setVisible(false);
        
    }
    

Connection con1;
PreparedStatement pst;
PreparedStatement insert;
ResultSet rs;
DefaultTableModel model = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   private void hutangnya()
   {       
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/akrab_main","root","");
            pst = con1.prepareStatement("select * from pengguna");
            ResultSet rs = pst.executeQuery();
            
            hutang2.removeAllItems();          
            while(rs.next())
            {                
                hutang2.addItem(rs.getString(2) );    
            }                     
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        popupMenu3 = new java.awt.PopupMenu();
        jPasswordField1 = new javax.swing.JPasswordField();
        satusatu = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        hutang2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        hutang3 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        tambah1 = new javax.swing.JButton();
        boxhapus = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jumlah4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablewarung = new javax.swing.JTable();
        typenya = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bayar = new javax.swing.JTextField();
        subtotal = new javax.swing.JTextField();
        hutang1 = new javax.swing.JTextField();
        wajib1 = new javax.swing.JLabel();
        hasilhutang = new javax.swing.JTextField();
        bayar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        wajibminus = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kolomkategori = new javax.swing.JTable();
        jTextCari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        namabarang2 = new javax.swing.JTextField();
        satuannya = new javax.swing.JTextField();
        harga3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        wajibteks = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ngayahna = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        bacode1 = new javax.swing.JTextField();
        riwa = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        hutangna = new javax.swing.JTextField();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        popupMenu3.setLabel("popupMenu3");

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        satusatu.setBackground(new java.awt.Color(0, 102, 102));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setForeground(new java.awt.Color(0, 0, 102));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));

        hutang2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hutang2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.green, java.awt.Color.green));
        hutang2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hutang2ItemStateChanged(evt);
            }
        });
        hutang2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                hutang2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        hutang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hutang2MouseClicked(evt);
            }
        });
        hutang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hutang2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Memiliki Hutang");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pilih Pelanggan");

        hutang3.setEditable(false);
        hutang3.setText("HUTANGNYA");
        hutang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hutang3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(hutang3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hutang3)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(hutang2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(312, 312, 312))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hutang2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
        );

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));

        tambah1.setBackground(new java.awt.Color(0, 153, 0));
        tambah1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tambah1.setForeground(new java.awt.Color(255, 255, 255));
        tambah1.setText("Tambah");
        tambah1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah1MouseClicked(evt);
            }
        });
        tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah1ActionPerformed(evt);
            }
        });

        boxhapus.setBackground(new java.awt.Color(255, 0, 0));
        boxhapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boxhapus.setForeground(new java.awt.Color(255, 255, 255));
        boxhapus.setText("Hapus");
        boxhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambah1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(boxhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        jumlah4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlah4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 255, 51), java.awt.Color.green));
        jumlah4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jumlah4KeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mau Beli Berapa ?");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlah4)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        tablewarung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tablewarung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Nama Barang", "Satuan", "Harga", "Jumlah", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablewarung.setRowHeight(35);
        tablewarung.setRowMargin(3);
        tablewarung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablewarungMouseClicked(evt);
            }
        });
        tablewarung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablewarungKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablewarung);
        if (tablewarung.getColumnModel().getColumnCount() > 0) {
            tablewarung.getColumnModel().getColumn(0).setPreferredWidth(0);
            tablewarung.getColumnModel().getColumn(0).setMaxWidth(1);
            tablewarung.getColumnModel().getColumn(1).setPreferredWidth(200);
            tablewarung.getColumnModel().getColumn(2).setMaxWidth(500);
        }

        typenya.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        typenya.setForeground(new java.awt.Color(255, 255, 255));
        typenya.setText("s");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama :");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        bayar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bayar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 255, 51), java.awt.Color.green));
        bayar.setCaretColor(new java.awt.Color(102, 204, 0));
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayarKeyReleased(evt);
            }
        });

        subtotal.setEditable(false);
        subtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subtotal.setText("SUBTOTAL");
        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });

        hutang1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hutang1.setText("-0");
        hutang1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, new java.awt.Color(255, 0, 0)));
        hutang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hutang1ActionPerformed(evt);
            }
        });
        hutang1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hutang1KeyReleased(evt);
            }
        });

        wajib1.setForeground(new java.awt.Color(255, 51, 51));
        wajib1.setText("Wajib di isi");

        hasilhutang.setEditable(false);
        hasilhutang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hasilhutang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hasilhutangKeyReleased(evt);
            }
        });

        bayar1.setBackground(new java.awt.Color(0, 153, 0));
        bayar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bayar1.setForeground(new java.awt.Color(255, 255, 255));
        bayar1.setText("PRINT");
        bayar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bayar1MouseClicked(evt);
            }
        });
        bayar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayar1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tunai");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Subtotal");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tambah Hutang");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sisa");

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("BARU");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        wajibminus.setForeground(new java.awt.Color(255, 51, 51));
        wajibminus.setText("Wajib diberi tanda minus \"-\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wajib1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hutang1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hasilhutang, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(wajibminus, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasilhutang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hutang1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wajib1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wajibminus)
                .addGap(87, 87, 87))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        kolomkategori.setAutoCreateRowSorter(true);
        kolomkategori.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kolomkategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Barcode", "Barang", "Satuan", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kolomkategori.setAlignmentX(1.0F);
        kolomkategori.setAlignmentY(1.0F);
        kolomkategori.setMinimumSize(new java.awt.Dimension(80, 70));
        kolomkategori.setRowHeight(27);
        kolomkategori.setRowMargin(9);
        kolomkategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kolomkategoriMouseClicked(evt);
            }
        });
        kolomkategori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kolomkategoriKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(kolomkategori);
        if (kolomkategori.getColumnModel().getColumnCount() > 0) {
            kolomkategori.getColumnModel().getColumn(0).setMinWidth(0);
            kolomkategori.getColumnModel().getColumn(0).setMaxWidth(0);
            kolomkategori.getColumnModel().getColumn(2).setMinWidth(100);
            kolomkategori.getColumnModel().getColumn(2).setMaxWidth(700);
        }

        jTextCari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCariActionPerformed(evt);
            }
        });
        jTextCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextCariKeyReleased(evt);
            }
        });

        jButton1.setText("Tambah Barang");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah Barang");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        namabarang2.setEditable(false);
        namabarang2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        namabarang2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.red));
        namabarang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namabarang2ActionPerformed(evt);
            }
        });

        satuannya.setEditable(false);
        satuannya.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        harga3.setEditable(false);
        harga3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cari");

        jButton7.setText("Refresh");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextCari, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(namabarang2)
                                .addGap(18, 18, 18)
                                .addComponent(satuannya, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(harga3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namabarang2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(harga3)
                        .addComponent(satuannya)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCari, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );

        wajibteks.setForeground(new java.awt.Color(255, 51, 51));
        wajibteks.setText("SAMPAI ADA NAMA BARANGNYA!");

        javax.swing.GroupLayout satusatuLayout = new javax.swing.GroupLayout(satusatu);
        satusatu.setLayout(satusatuLayout);
        satusatuLayout.setHorizontalGroup(
            satusatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(satusatuLayout.createSequentialGroup()
                .addGroup(satusatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(satusatuLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(satusatuLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(satusatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(satusatuLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(typenya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(satusatuLayout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(2, 2, 2))
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(satusatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(satusatuLayout.createSequentialGroup()
                        .addComponent(wajibteks)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(satusatuLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))))
        );
        satusatuLayout.setVerticalGroup(
            satusatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(satusatuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(satusatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(typenya)
                    .addComponent(wajibteks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(satusatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(satusatuLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        ngayahna.setEditable(false);
        ngayahna.setBackground(new java.awt.Color(153, 153, 153));
        ngayahna.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ngayahna.setForeground(new java.awt.Color(255, 255, 255));
        ngayahna.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ngayahna.setBorder(null);
        ngayahna.setDragEnabled(true);
        ngayahna.setInheritsPopupMenu(true);
        ngayahna.setSelectedTextColor(new java.awt.Color(240, 240, 240));
        ngayahna.setSelectionColor(new java.awt.Color(240, 240, 240));
        ngayahna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngayahnaActionPerformed(evt);
            }
        });
        ngayahna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ngayahnaKeyReleased(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(0, 0, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TOKO LINA -  UMUM V6");

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("GROSIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Hutang");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("LAPORAN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        bacode1.setText("jTextField1");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bacode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bacode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        riwa.setBackground(new java.awt.Color(0, 0, 153));
        riwa.setForeground(new java.awt.Color(0, 0, 153));
        riwa.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153)));

        jTextField1.setBackground(new java.awt.Color(0, 0, 153));
        jTextField1.setForeground(new java.awt.Color(0, 0, 153));
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153)));

        hutangna.setText("Tidak Ada");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(riwa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hutangna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(476, 476, 476)
                .addComponent(ngayahna, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(444, 444, 444))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(ngayahna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(riwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hutangna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1349, Short.MAX_VALUE)
            .addComponent(satusatu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(satusatu, javax.swing.GroupLayout.PREFERRED_SIZE, 633, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    
    
     private void kasirku()
    {
         String barcode = bacode1.getText();
            
        try {
            Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/akrab_main","root","");
                insert = con1.prepareStatement("select * from barang where barcode=?");
                insert.setString(1,barcode);   
                rs = insert.executeQuery();
                
                while(rs.next())
                {
                    int qty;
                    int currentqty;
                    currentqty = rs.getInt("qty");
                    qty = rs.getInt("qty");
                    
                    //masuk tabel
                    int harga = Integer.parseInt(harga3.getText());
                    int qtynew = Integer.parseInt(jumlah4.getText());
                    
                    int tot = harga * qtynew;
                    
                    if(qtynew >= currentqty)
                    {
                        JOptionPane.showMessageDialog(this,"Stok hanya tersedia " + "= " +currentqty);
                        JOptionPane.showMessageDialog(this,"Stok kosong, harap tambahkan");
                    }
                    
                    else
                    {
                        model = (DefaultTableModel)tablewarung.getModel();
                        model.addRow(new Object[]
                        {
                        bacode1.getText(),
                        namabarang2.getText(),
                        satuannya.getText(),
                      
                        harga3.getText(),
                        jumlah4.getText(),
                        
                        tot,
                        }
                        );
                        
                        int sum=0;
                        for(int i=0; i<tablewarung.getRowCount(); i++)
                                {
                                    
                                    
                                    sum = sum + Integer.parseInt(tablewarung.getValueAt(i,5).toString());
                                    
                                    
                                }   
                              
                               bacode1.setText("");
                               namabarang2.setText("");
                               satuannya.setText("");
                               harga3.setText("");
                               jumlah4.setText("");   
                               subtotal.setText(Integer.toString(sum));
                               
                        }
                                }
                
                
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(kasirumum.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(kasirumum.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }

   
    
    private void sales()
    {
      DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        String date = dtf.format(now);
        
          String nama_pelanggan = hutang2.getSelectedItem().toString();
       String hutangsekarang= hutang1.getText();
        String bayarin = bayar.getText();
        // String tunai = bayar.getText();
          String subtot = subtotal.getText();
       // Int hutang = hutang1.getText();
        String bal =ngayahna.getText();
        
         int uang1 =Integer.parseInt(bayar.getText());
        int uang2 = Integer.parseInt(subtotal.getText());
        int uang3 = uang1 - uang2;
        int hutangsia =Integer.parseInt(hutang3.getText());
        String lunas = hutangna.getText();
        int hutang = uang3 + hutangsia;   

        
        //
    
        int lastinsetid =0;
        try {
     if (hutang < -1) {
        Class.forName("com.mysql.jdbc.Driver");
        con1 = DriverManager.getConnection("jdbc:mysql://localhost/akrab_main","root","");
        String query = "insert into sales(nama_pelanggan,date,subtotal,bayar,balance,hutang,totalhutang)values(?,?,?,?,?,?,?)";
        
        insert = con1.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
        
        insert.setString(1, nama_pelanggan);
        insert.setString(2, date);
        insert.setString(3, subtot);
        insert.setString(4, bayarin);
        insert.setString(5, bal);
        insert.setString(6, hutangsekarang);
        insert.setInt(7, hutang);
      

       
        
        insert.executeUpdate();
        ResultSet genteratedKeyResult = insert.getGeneratedKeys();
        
        if(genteratedKeyResult.next())
          {
             lastinsetid = genteratedKeyResult.getInt(1);

           }
        
     }else {
         
         Class.forName("com.mysql.jdbc.Driver");
        con1 = DriverManager.getConnection("jdbc:mysql://localhost/akrab_main","root","");
        String query = "insert into sales(nama_pelanggan,date,subtotal,bayar,balance,hutang,totalhutang)values(?,?,?,?,?,?,?)";
        
        insert = con1.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
        
        insert.setString(1, nama_pelanggan);
        insert.setString(2, date);
        insert.setString(3, subtot);
        insert.setString(4, bayarin);
        insert.setString(5, bal);
        insert.setString(6, hutangsekarang);
        insert.setString(7, lunas);
      

       
        
        insert.executeUpdate();
        ResultSet genteratedKeyResult = insert.getGeneratedKeys();
        
        if(genteratedKeyResult.next())
          {
             lastinsetid = genteratedKeyResult.getInt(1);

           }
     }
        //table sales barang
        
        int rows = tablewarung.getRowCount();
        String query1 = "insert into sales_barang(lastinsetid,pelanggan,nama_barang,barcode,jumlah,hargatotal,harga,satuan,subtotal,kembalian,hutang_sebelumnya)values(?,?,?,?,?,?,?,?,?,?,?)";
        insert = con1.prepareStatement(query1); 
        
        String pelanggan = hutang2.getSelectedItem().toString();
        
        String nama_barang="";
        String barcode="";
      
        String jumlah="";
       
        String harga="";
        String satuan="";
        //String tunai="";
        //String subtotal="";
       // String tambahhutang="";
        //String kembalian="";
        String kembalian = ngayahna.getText();
      //  String hutangsebelumnnya="";
        int hargatotal=0;
         String subtotal1 = subtotal.getText();
         String hutangsebelumnnya = hutang3.getText();
         
       

        for(int i=0; i<tablewarung.getRowCount(); i++)
        {
    
            barcode= (String)tablewarung.getValueAt(i,0);
            nama_barang= (String)tablewarung.getValueAt(i,1);
            satuan= (String)tablewarung.getValueAt(i,2);
            harga= (String)tablewarung.getValueAt(i,3);
            jumlah= (String)tablewarung.getValueAt(i,4);
            hargatotal= (int)tablewarung.getValueAt(i,5);
      
            
            
            
            
            insert.setInt(1, lastinsetid);
            insert.setString(2, pelanggan);
         
insert.setString(3, nama_barang);
insert.setString(4, barcode);
insert.setString(5, jumlah);
   insert.setInt(6, hargatotal);
insert.setString(7, harga);
insert.setString(8, satuan);

insert.setString(9, subtotal1);

insert.setString(10, kembalian);
         
insert.setString(11, hutangsebelumnnya);

//            insert.setInt(1, id);
         insert.executeUpdate();

            //
            
 //JOptionPane.showMessageDialog(null, "DATA!");
            //
            

        }
        
        
        //pengurangan stok
        String query3 = "update barang set qty= qty+? where barcode=?";
        insert = con1.prepareStatement(query3);
        
        for(int i=0; i<tablewarung.getRowCount(); i++)
        {
            barcode= (String)tablewarung.getValueAt(i,0);
            jumlah= (String)tablewarung.getValueAt(i,4);
          
            
            insert.setString(1, jumlah);
            insert.setString(2, barcode);
            insert.executeUpdate();
            
        }

        insert.addBatch();
      
        
                    HashMap m = new HashMap();
        m.put("noNota",lastinsetid);
            try {
                
                
                JasperDesign jdesign = JRXmlLoader.load("C:\\kasir\\cetak.jrxml");
                JasperReport ireport = JasperCompileManager.compileReport(jdesign); 
            JasperPrint jprint = JasperFillManager.fillReport(ireport,m,con1);
           
            //JasperViewer.viewReport(jprint);
            JasperPrintManager.printReport(jprint,false);
            
            } catch (JRException ex) {
                Logger.getLogger(kasirumum.class.getName()).log(Level.SEVERE, null, ex);
            }
    
            
            
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(kasirumum.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
            Logger.getLogger(kasirumum.class.getName()).log(Level.SEVERE, null, ex);
             }
        
}
    
    public void print()
    {
        
      String pelanggan= hutang2.getSelectedItem().toString();
        String sub = subtotal.getText();
        String pay = bayar.getText();
        String hutang = hutang1.getText();
        String hutangkemarin = hutang3.getText();
        String bal = ngayahna.getText();
        
        try {
            new print(pelanggan,sub,pay,bal,hutang,hutangkemarin,tablewarung.getModel()).setVisible(true);
        } catch (PrinterException ex) {
            Logger.getLogger(kasirumum.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
     private void table_update()
    {
        try {
            int c;
            
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/akrab_main","root","");
                pst = con1.prepareStatement("select p.kode_item,p.barcode,p.barang,p.jenis,p.hargaumum,c.kategori,p.qty,b.suplayer,p.status from barang p,kategori c,satuan d,suplayer b where p.id = c.id and p.idsatuan = d.idsatuan and p.idsup = b.idsup");
                ResultSet rs = pst.executeQuery();
                ResultSetMetaData rsd =rs.getMetaData();
                c = rsd.getColumnCount();
                DefaultTableModel d = (DefaultTableModel)kolomkategori.getModel();  
                d.setRowCount(0);
                
                while(rs.next()){
                    Vector v2 = new Vector();
                    
                    for(int i=1; i<=c; i++)
                    {
                        
                        
                        v2.add(rs.getString("barcode"));
                        v2.add(rs.getString("barang"));
                        v2.add(rs.getString("jenis"));
                        v2.add(rs.getString("hargaumum"));
                       
                    
                    }
                    d.addRow(v2);
                }
                
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
    
    private void tampilData(){
        try{
            Object[] judul_kolom = {"barang", "barcode", "jenis", "hargaumum"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            kolomkategori.setModel(tabModel);
            
            Connection conn=(Connection)koneksicari.koneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RsProduk=stt.executeQuery("SELECT * from barang ");  
            while(RsProduk.next()){
                Object[] data={
                    RsProduk.getString("barcode"),
                    RsProduk.getString("barang"),
                    RsProduk.getString("jenis"),
                    RsProduk.getString("hargaumum"),
                             
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }

private void cariData(String key){
        try{
               Object[] judul_kolom = { "barcode","barang", "jenis", "hargaumum"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            kolomkategori.setModel(tabModel);
            
            Connection conn=(Connection)koneksicari.koneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RsProduk=stt.executeQuery("SELECT * from barang WHERE kode_item LIKE '%"+key+"%' OR barang LIKE '%"+key+"%' OR jenis LIKE '%"+key+"%'");  
            while(RsProduk.next()){
                Object[] data={
                   RsProduk.getString("barcode"),
                    RsProduk.getString("barang"),
                    
                    RsProduk.getString("jenis"),
                    RsProduk.getString("hargaumum"),
                           
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new kasirumum().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ngayahnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngayahnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayahnaActionPerformed

    private void ngayahnaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ngayahnaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayahnaKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(kasirumum.MAXIMIZED_BOTH);

    }//GEN-LAST:event_formWindowOpened

    private void jTextCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCariKeyReleased
        // TODO add your handling code here:
        String key=jTextCari.getText();
        System.out.println(key);

        if(key!=""){
            cariData(key);
        }else{
            tampilData();
        }
        
               TableColumn column;
        kolomkategori.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = kolomkategori.getColumnModel().getColumn(0); 
        column.setPreferredWidth(0);
        column = kolomkategori.getColumnModel().getColumn(1); 
        column.setPreferredWidth(270); 
        column = kolomkategori.getColumnModel().getColumn(2); 
        column.setPreferredWidth(80); 
        column = kolomkategori.getColumnModel().getColumn(3); 
        column.setPreferredWidth(150); 
    }//GEN-LAST:event_jTextCariKeyReleased

    private void kolomkategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kolomkategoriMouseClicked
        // TODO add your handling code here:

        DefaultTableModel d1 = (DefaultTableModel)kolomkategori.getModel();
        int selectIndex = kolomkategori.getSelectedRow();

        bacode1.setText(d1.getValueAt(selectIndex, 0).toString());
        namabarang2.setText(d1.getValueAt(selectIndex, 1).toString());
        satuannya.setText(d1.getValueAt(selectIndex, 2).toString());
        harga3.setText(d1.getValueAt(selectIndex, 3).toString());

    }//GEN-LAST:event_kolomkategoriMouseClicked

     private void riwayathutang() throws SQLException
    {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        String date = dtf.format(now);
        String nama_pelanggan = hutang2.getSelectedItem().toString();
        String hutang = hutang1.getText();
        String dibayar = riwa.getText();
 
        
        //
    
        int lastinsetid =0;
        try {
     
        Class.forName("com.mysql.jdbc.Driver");
        con1 = DriverManager.getConnection("jdbc:mysql://localhost/akrab_main","root","");
        String query = "insert into riwayathutang(nama,tanggal,hutang,dibayar)values(?,?,?,?)";
        
        insert = con1.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
        
        insert.setString(1, nama_pelanggan);
        insert.setString(2, date);
        insert.setString(3, hutang);
        insert.setString(4, dibayar);
      

       
        
        insert.executeUpdate();
        ResultSet genteratedKeyResult = insert.getGeneratedKeys();
        
        if(genteratedKeyResult.next())
          {
             lastinsetid = genteratedKeyResult.getInt(1);

           }
        
       

             } catch (ClassNotFoundException ex) {
        Logger.getLogger(kasir2.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    private void bayar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayar1ActionPerformed
        // TODO add your handling code here:
       // sales();
        jButton6.setVisible(true);
        ngayahna.setVisible(true);
        //Hasil Hutang
        int bayarin =Integer.parseInt(bayar.getText());
        int subtotalnya = Integer.parseInt(subtotal.getText());
        int bal = bayarin - subtotalnya;
        int hutangsia =Integer.parseInt(hutang3.getText());

        int hasilnya = bal + hutangsia;
        hasilhutang.setText(String.valueOf(bal));
        ngayahna.setText(String.valueOf(hasilnya));

        //ngurangin hutang ke database

        if (bal < -1){

            String nama_pelanggan1 = hutang2.getSelectedItem().toString();
            String hutang2 = hutang1.getText();

            int lastinsetid =0;
            try {

                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/akrab_main","root","");
                String query = "insert into pelanggan(nama_pelanggan,hutang)values(?,?)";
                insert = con1.prepareStatement(query);

                insert = con1.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);

                insert.setString(2, hutang2);
                insert.setString(1, nama_pelanggan1);

                insert.executeUpdate();
                ResultSet genteratedKeyResult = insert.getGeneratedKeys();

                if(genteratedKeyResult.next())
                {
                    lastinsetid = genteratedKeyResult.getInt(1);

                }

                if (hutang1.getText().equals("-0")){

                    wajib1.setVisible(true);
                }   else if (hutang1.getText().equals("")) {
                    wajibminus.setVisible(true);

                   
                } else {
                    wajibminus.setVisible(false);
                    wajib1.setVisible(false);
                    //print();
                    riwayathutang();
                   sales();
                }
                 
                
                insert.addBatch();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(kasirumum.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(kasirumum.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if( bal > 0) {

            //Hasil Hutang

            //ngurangin hutang ke database

            //print();
sales();
            String nama_pelanggan1 = hutang2.getSelectedItem().toString();
            String hutang2 = hasilhutang.getText();

            int lastinsetid =0;
            try {

                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/akrab_main","root","");
                String query = "insert into pelanggan(nama_pelanggan,hutang)values(?,?)";
                insert = con1.prepareStatement(query);

                insert = con1.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);

                insert.setString(2, hutang2);
                insert.setString(1, nama_pelanggan1);

                insert.executeUpdate();
                ResultSet genteratedKeyResult = insert.getGeneratedKeys();

                if(genteratedKeyResult.next())
                {
                    lastinsetid = genteratedKeyResult.getInt(1);

                }
                insert.addBatch();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(kasirumum.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(kasirumum.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
         
    }//GEN-LAST:event_bayar1ActionPerformed

    private void bayar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayar1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_bayar1MouseClicked

    private void hasilhutangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hasilhutangKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilhutangKeyReleased

    private void hutang1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hutang1KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_hutang1KeyReleased

    private void hutang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hutang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hutang1ActionPerformed

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalActionPerformed

    private void bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyReleased
        // TODO add your handling code here:

        String output;
        int a = Integer.valueOf(bayar.getText());
        int b = Integer.valueOf(subtotal.getText());
        int hasil = a - b;
        output = String.valueOf(hasil);
        hasilhutang.setText(output);

        String sby = hasilhutang.getText().replaceAll("\\,", "");
        double sbyr= Double.parseDouble(sby);
        DecimalFormat df = new DecimalFormat("#,###,##0");

        if (sbyr>999){
            hasilhutang.setText(df.format(sbyr));

        }

    }//GEN-LAST:event_bayarKeyReleased

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void tablewarungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablewarungMouseClicked
        //Pilih Tabel
        // TODO add your handling code here:
    }//GEN-LAST:event_tablewarungMouseClicked

    private void boxhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxhapusActionPerformed
        // TODO add your handling code here:

        model.removeRow(tablewarung.getSelectedRow());
        int sum = 0;
        for(int i=0; i<tablewarung.getRowCount(); i++)

        {
            sum = sum + Integer.parseInt(tablewarung.getValueAt(i,5).toString());

        }
        subtotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_boxhapusActionPerformed

    private void hutang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hutang3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_hutang3ActionPerformed

    private void hutang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hutang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hutang2ActionPerformed

    private void hutang2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hutang2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hutang2MouseClicked

    private void hutang2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_hutang2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:

    }//GEN-LAST:event_hutang2PopupMenuWillBecomeInvisible

    private void hutang2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hutang2ItemStateChanged
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/akrab_main","root","");
            String pelanggan = hutang2.getSelectedItem().toString();

            pst = con1.prepareStatement("select hutang from pengguna where nama_pelanggan = ?");
            pst.setString(1, pelanggan);
            ResultSet rs = pst.executeQuery();

            if(rs.next()==true)
            {

                String hutang = rs.getString(1);
                hutang3.setText(hutang);

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(barang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_hutang2ItemStateChanged

    private void tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah1ActionPerformed
        // TODO add your handling code here:
        kasirku();
        bayar.setVisible(true);
        if (namabarang2.getText().equals("")){
  JOptionPane.showMessageDialog(null, "Double klik barangnya!");
                    wajibteks.setVisible(true);
                    
                }  else  {
            
           wajibteks.setVisible(false);
                }
    }//GEN-LAST:event_tambah1ActionPerformed

    private void tambah1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tambah1MouseClicked

    private void jTextCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCariActionPerformed

    private void namabarang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namabarang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namabarang2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new tambahbarang().setVisible(true);
          
       // this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new updatebarang().setVisible(true);
         //this.setVisible(false);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            new kasir2().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          new updatepengguna().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new laporan().setVisible(true);
         this.setVisible(false); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCariKeyPressed
        // TODO add your handling code here:
        
        switch(evt.getKeyCode()){
            case 40:kolomkategori.requestFocus();
            break;
        }
    }//GEN-LAST:event_jTextCariKeyPressed

    private void jumlah4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah4KeyPressed
        // TODO add your handling code here:

             if (evt.getKeyCode()==KeyEvent.VK_ENTER){
                bayar.requestFocus();
                 kasirku();
                 
             }
             

    }//GEN-LAST:event_jumlah4KeyPressed

    private void kolomkategoriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolomkategoriKeyPressed
        // TODO add your handling code here:
             if (evt.getKeyCode()==KeyEvent.VK_ENTER){
                        DefaultTableModel d1 = (DefaultTableModel)kolomkategori.getModel();
        int selectIndex = kolomkategori.getSelectedRow();

        bacode1.setText(d1.getValueAt(selectIndex, 0).toString());
        namabarang2.setText(d1.getValueAt(selectIndex, 1).toString());
        satuannya.setText(d1.getValueAt(selectIndex, 2).toString());
        harga3.setText(d1.getValueAt(selectIndex, 3).toString());
                 
                 
                 jumlah4.requestFocus();
                 
             }
    }//GEN-LAST:event_kolomkategoriKeyPressed

    private void tablewarungKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablewarungKeyPressed
        // TODO add your handling code here:
                     if (evt.getKeyCode()==KeyEvent.VK_ENTER){
                 bayar.requestFocus();
             }
    }//GEN-LAST:event_tablewarungKeyPressed

    private void bayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyPressed
        // TODO add your handling code here:
                if (evt.getKeyCode()==KeyEvent.VK_ENTER){
                 bayar1.requestFocus();
             }
    }//GEN-LAST:event_bayarKeyPressed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)kolomkategori.getModel();
        model.setRowCount(0);
        table_update();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasirumum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasirumum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasirumum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasirumum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasirumum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bacode1;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton bayar1;
    private javax.swing.JButton boxhapus;
    private javax.swing.JTextField harga3;
    private javax.swing.JTextField hasilhutang;
    private javax.swing.JTextField hutang1;
    private javax.swing.JComboBox hutang2;
    private javax.swing.JTextField hutang3;
    private javax.swing.JTextField hutangna;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextCari;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jumlah4;
    private javax.swing.JTable kolomkategori;
    private javax.swing.JTextField namabarang2;
    private javax.swing.JTextField ngayahna;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private java.awt.PopupMenu popupMenu3;
    private javax.swing.JTextField riwa;
    private javax.swing.JTextField satuannya;
    private javax.swing.JPanel satusatu;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTable tablewarung;
    private javax.swing.JButton tambah1;
    private javax.swing.JLabel typenya;
    private javax.swing.JLabel wajib1;
    private javax.swing.JLabel wajibminus;
    private javax.swing.JLabel wajibteks;
    // End of variables declaration//GEN-END:variables




}
