/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.print.PrinterException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class print extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public print() {
        initComponents();
    }
    
    String sub1;
    String pay1;
    String hutang;
    String bal1;
    String user;
    String hutangkemarinnya;
    
    
    
     public print(String pelanggan,String sub,String pay, String bal,String hutang,String hutangkemarin,TableModel tableModel) throws PrinterException {
    
    initComponents();
    int detik, menit, jam, hari, bulan, tahun;
    GregorianCalendar date = new GregorianCalendar();
    String namabulan[] = {"Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"};
    detik = date.get(Calendar.SECOND);
    menit = date.get(Calendar.MINUTE);
    jam =  date.get(Calendar.HOUR_OF_DAY);
    hari = date.get(Calendar.DAY_OF_MONTH);
    bulan = date.get(Calendar.MONTH);
    tahun = date.get(Calendar.YEAR);
    
        this.sub1= sub;
        this.user = pelanggan;
        this.pay1= pay;
        this.bal1= bal;
        this.hutangkemarinnya= hutangkemarin;
        this.hutang= hutang;
        
          nota.setText(nota.getText()+"               TOKO LINA\n");
          nota.setText(nota.getText()+"-------------------------------------\n");
          nota.setText(nota.getText()+" Pembeli: "+pelanggan);
          nota.setText(nota.getText()+"\n");
          nota.setText(nota.getText()+" Transaksi: "+hari+" "+namabulan[bulan]+" "+tahun);
          nota.setText(nota.getText()+"\n");
  
         nota.setText(nota.getText()+"\n");
         for(int i=0; i<tableModel.getRowCount(); i++)
        {
            String jumlah = (String) tableModel.getValueAt(i, 4);
            String nama = (String) tableModel.getValueAt(i, 1);
            String satuan = (String) tableModel.getValueAt(i, 2);
            String harga = (String) tableModel.getValueAt(i, 3);
            int total = (int) tableModel.getValueAt(i, 5);           
            String jumlahhutang = hutangkemarin+hutang;

            nota.setText(nota.getText()+" "+nama);
            nota.setText(nota.getText()+"\n");
            nota.setText(nota.getText()+" "+jumlah+ "  "+satuan+"    X    Rp." +""+harga+"   =   Rp."+total);
            nota.setText(nota.getText()+"\n");
        }
   
        nota.setText(nota.getText()+"                               ------- +");
        nota.setText(nota.getText()+"\n");
                nota.setText(nota.getText()+"   " + "                Subtotal : "+" Rp."+ sub+ "\n");
        nota.setText(nota.getText()+"-------------------------------------\n");

        nota.setText(nota.getText()+"   " + "Hutang Sekarang :  "+ hutang+ "\n");
        nota.setText(nota.getText()+"   " + "Hutang Sebelumnya :  "+ hutangkemarin+ "\n");
       //     nota.setText(nota.getText()+"   " + "Total Hutang :  "+ jumlahhutang+ "\n");
        nota.setText(nota.getText()+"   " + "Tunai :  "+ pay+ "\n");
        nota.setText(nota.getText()+"   " + "Total :  "+ bal+ "\n");
          nota.setText(nota.getText()+"\n");
        nota.setText(nota.getText()+"-------------------------------------\n");
        nota.print();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        nota = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        nota.setEditable(false);
        nota.setColumns(20);
        nota.setFont(new java.awt.Font("Monospaced", 0, 7)); // NOI18N
        nota.setRows(5);
        nota.setTabSize(3);
        nota.setAlignmentX(0.1F);
        nota.setAlignmentY(0.1F);
        nota.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nota.setMaximumSize(new java.awt.Dimension(500, 1000));
        nota.setMinimumSize(new java.awt.Dimension(200, 100));
        nota.setPreferredSize(new java.awt.Dimension(500, 1000));
        jScrollPane1.setViewportView(nota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea nota;
    // End of variables declaration//GEN-END:variables
}
